version: '3'
services:
  myapplication:
    image: mongodb/mongodb-community-server:6.0-ubi8
    environment:
      - CONN_STR=mongodb://brightemmanuel97:EVGPQWYkTktf8jmi@mongodb
    command: '/bin/bash -c "sleep 5; mongosh $$CONN_STR --eval \"show dbs;\""'
    depends_on:
      - mongodb
  mongodb:
    image: mongodb/mongodb-community-server:6.0-ubi8
    environment:
      - MONGO_INITDB_ROOT_USERNAME=brightemmanuel97
      - MONGO_INITDB_ROOT_PASSWORD=EVGPQWYkTktf8jmi
    volumes:
      - type: bind
        source: ./data
        target: /data/db